- category: Administrative
  description: Any specifically defined piece of work that is undertaken or attempted
    to meet a single requirement.
  foreignKeys:
  - sourceField: lab
    targetEntity: Lab
    targetField: name
  links:
  - label: Project references the Program it is part of.
    name: Program
    required: 'True'
  name: Project
  primaryKey: name
  properties:
  - dataType: String
    maxLength: 255
    name: name
    required: true
    unique: true
  - dataType: String
    maxLength: 65000
    name: description
    required: false
  - dataType: String
    maxLength: 255
    name: program
    required: false
  uniqueKeys:
  - - project_id
    - project_submitter_id
