type AliquotRunMetadata {
	aliquot_run_metadata_id: String
	aliquot_submitter_id: String
	aliquot_id: String
	label: String
	experiment_number: Int
	fraction: String
	replicate_number: String
	date: Date
	alias: String
	analyte: String
	aliquot: Aliquot
	protocol: Protocol
	study: Study
}