type Aliquot {
	aliquot_id: String
	aliquot_submitter_id: String
	status: String
	aliquot_is_ref: String
	pool: String
	sample_id: String
	sample_submitter_id: String
	case_id: String
	case_submitter_id: String
	aliquot_quantity: Float
	aliquot_volume: Float
	amount: Float
	analyte_type: String
	concentration: Float
	aliquot_run_metadata: [AliquotRunMetadata]
	sample: Sample
	project: Project
}