type Case {
  case_id: String
  case_submitter_id: String
  project_submitter_id: String
  project_id: String
  case_is_ref: String
  tissue_source_site_code: String
  days_to_lost_to_followup: Int
  disease_type: String
  index_date: String
  lost_to_followup: String
  primary_site: String
  consent_type: String
  days_to_consent: String
  externalReferences: [EntityReference]
  demographics: [Demographic]  
  samples: [Sample]
  diagnoses: [Diagnosis]
  exposures: [Exposure]
  family_histories: [FamilyHistory]
  follow_ups: [FollowUp]
  treatments: [Treatment]
  count: Int
}