type Demographic {
	demographic_id: String
	demographic_submitter_id: String
	ethnicity: String
	gender: String
	race: String
	cause_of_death: String
	days_to_birth: String
	days_to_death: String
	vital_status: String
	year_of_birth: String
	year_of_death: String 
	case: Case
	project: Project
}