type EntityReference {
	reference_id: String
	entity_type: String
	entity_id: String
	external_reference_id: String
	reference_type: String
	reference_entity_type: String
	reference_entity_alias: String
	submitter_id_name: String
	reference_resource_name: String
	reference_resource_shortname: String
	reference_entity_location: String
	annotation: String
}