type Exposure {
	exposure_id: String
	exposure_submitter_id: String
	case_id: String
	case_submitter_id: String
	project_id: String
	project_submitter_id: String
	alcohol_days_per_week: String
	alcohol_drinks_per_day: String
	alcohol_history: String
	alcohol_intensity: String
	asbestos_exposure: String
	cigarettes_per_day: String
	coal_dust_exposure: String
	environmental_tobacco_smoke_exposure: String
	pack_years_smoked: String
	radon_exposure: String
	respirable_crystalline_silica_exposure: String
	smoking_frequency: String
	time_between_waking_and_first_smoke: String
	tobacco_smoking_onset_year: String
	tobacco_smoking_quit_year: String
	tobacco_smoking_status: String
	type_of_smoke_exposure: String
	type_of_tobacco_used: String
	years_smoked: String
	age_at_onset: String
	alcohol_type: String
	exposure_duration: String
	exposure_duration_years: String
	exposure_type: String
	marijuana_use_per_week: String
	parent_with_radiation_exposure: String
	secondhand_smoke_as_child: String
	smokeless_tobacco_quit_age: String
	tobacco_use_per_day: String
}