type FollowUp {
	 follow_up_id: String
	 follow_up_submitter_id: String
	 case_id: String
	 case_submitter_id: String
	 project_id: String
	 project_submitter_id: String
	 adverse_event: String
	 barretts_esophagus_goblet_cells_present: String
	 bmi: String
	 cause_of_response: String
	 comorbidity: String
	 comorbidity_method_of_diagnosis: String
	 days_to_adverse_event: String
	 days_to_comorbidity: String
	 days_to_follow_up: String
	 days_to_progression: String
	 days_to_progression_free: String
	 days_to_recurrence: String
	 diabetes_treatment_type: String
	 disease_response: String
	 dlco_ref_predictive_percent: String
	 ecog_performance_status: String
	 fev1_ref_post_bronch_percent: String
	 fev1_ref_pre_bronch_percent: String
	 fev1_fvc_pre_bronch_percent: String
	 fev1_fvc_post_bronch_percent: String
	 height: String
	 hepatitis_sustained_virological_response: String
	 hpv_positive_type: String
	 karnofsky_performance_status: String
	 menopause_status: String
	 pancreatitis_onset_year: String
	 progression_or_recurrence: String
	 progression_or_recurrence_anatomic_site: String
	 progression_or_recurrence_type: String
	 reflux_treatment_type: String
	 risk_factor: String
	 risk_factor_treatment: String
	 viral_hepatitis_serologies: String
	 weight: String
}