type Gene {
  gene_id: String
  gene_name: String
  NCBI_gene_id: String
  authority: String
  description: String
  organism: String
  chromosome: String
  locus: String
  proteins: String
  assays: String
  spectral_counts: [Spectral_count]
}