type LegacyPublication {
	publication_id: String
	pubmed_id: String
	doi: String
	author: String
	title_legacy: String
	title: String
	journal: String
	journal_url: String
	year: String
	abstract: String
	citation: String
	studies: [Study]
	disease_types: [String]
	supplementary_data: [String]
}

