type Paginated {
	total: Int
	uiStudies: [UIStudy]
    uiFiles: [UIFile]
    uiLegacyFiles: [UIFile]
	uiCases: [UICase]
	uiClinical: [UIClinical]
	uiGenes: [UIGene]
	uiGeneStudySpectralCounts: [UIGeneStudySpectralCount]
	uiGeneAliquotSpectralCounts:[UIGeneStudySpectralCount]
	uiPtm: [UIPtm]
	uiPublication: [Publication]
	files: [File]
	cases: [Case]
	genesProper: [Gene]
	caseDiagnosesPerStudy: [Case]
	caseDemographicsPerStudy: [Case]
	caseExposuresPerStudy: [Case]
	caseFamilyHistoriesPerStudy: [Case]
	caseFollowUpsPerStudy: [Case]
	caseTreatmentsPerStudy: [Case]
	casesSamplesAliquots: [Case]
	genes: [SearchRecord]
	genesWithProtein: [SearchRecord]
	studies: [SearchStudyRecord]
	searchCases: [SearchCaseRecord]
	searchAliquots: [SearchAliquotRecord]
	spectralCounts: [Spectral_count]
	dataMatrix: [[String]]
	ptmDataMatrix: [[String]]
	pagination: Pagination
}