type PublicCase {
  case_id: String
  case_submitter_id: String
  project_id: String
  project_submitter_id: String
  disease_type: String
  primary_site: String
  externalReferences: [EntityReference]
}