type StudyExperimentalDesign {
	study_run_metadata_id: String
	study_run_metadata_submitter_id: String
	study_id: String
	study_submitter_id: String
	pdc_study_id: String
	aliquot_is_ref: String
	experiment_number: Int
	experiment_type: String
	plex_dataset_name: String
	acquisition_type: String
	number_of_fractions: String
	analyte: String
	label_free_asi: String
	itraq_113_asi: String
	itraq_114_asi: String
	itraq_115_asi: String
	itraq_116_asi: String
	itraq_117_asi: String
	itraq_118_asi: String
	itraq_119_asi: String
	itraq_121_asi: String
	tmt_126_asi: String
	tmt_127n_asi: String
	tmt_127c_asi: String
	tmt_128n_asi: String
	tmt_128c_asi: String
	tmt_129n_asi: String
	tmt_129c_asi: String
	tmt_129cc_asi: String
	tmt_130n_asi: String
	tmt_131_asi: String
	tmt_131c_asi: String
	tmt_132n_asi: String
	tmt_132c_asi: String
	tmt_133n_asi: String
	tmt_133c_asi: String
	tmt_134n_asi: String
	tmt_134c_asi: String
	tmt_135n_asi: String
	label_free: [LabelAliquot]
	itraq_113: [LabelAliquot]
	itraq_114: [LabelAliquot]
	itraq_115: [LabelAliquot]
	itraq_116: [LabelAliquot]
	itraq_117: [LabelAliquot]
	itraq_118: [LabelAliquot]
	itraq_119: [LabelAliquot]
	itraq_121: [LabelAliquot]
	tmt_126: [LabelAliquot]
	tmt_127n: [LabelAliquot]
	tmt_127c: [LabelAliquot]
	tmt_128n: [LabelAliquot]
	tmt_128c: [LabelAliquot]
	tmt_129n: [LabelAliquot]
	tmt_129c: [LabelAliquot]
	tmt_130c: [LabelAliquot]
	tmt_130n: [LabelAliquot]
	tmt_131: [LabelAliquot]
	tmt_131c: [LabelAliquot]
	tmt_132n: [LabelAliquot]
	tmt_132c: [LabelAliquot]
	tmt_133n: [LabelAliquot]
	tmt_133c: [LabelAliquot]
	tmt_134n: [LabelAliquot]
	tmt_134c: [LabelAliquot]
	tmt_135n: [LabelAliquot]
}