type Study {
  study_id: String
  study_submitter_id: String
  pdc_study_id: String
  submitter_id_name: String
  study_name: String
  study_shortname: String
  study_version: String
  is_latest_version: String
  embargo_date: Date
  program_name: String
  project_name: String
  program_id: String
  project_id: String
  project_submitter_id: String
  disease_type: String
  primary_site: String
  disease_types: [String]
  primary_sites: [String]
  analytical_fraction: String
  experiment_type: String
  acquisition_type: String
  project: Project
  cases_count: Int
  aliquots_count: Int
  contacts: [Contact]
  filesCount: [File]
  diagnoses: [Diagnosis]
  cases: [Case]
  files: [File]
  study_run_metadata: [StudyRunMetadata]
}