type Treatment {
	 treatment_id: String
	 treatment_submitter_id: String
	 case_id: String
	 case_submitter_id: String
	 project_id: String
	 project_submitter_id: String
	 days_to_treatment_end: String
	 days_to_treatment_start: String
	 initial_disease_status: String
	 regimen_or_line_of_therapy: String
	 therapeutic_agents: String
	 treatment_anatomic_site: String
	 treatment_effect: String
	 treatment_intent_type: String
	 treatment_or_therapy: String
	 treatment_outcome: String
	 treatment_type: String
	 chemo_concurrent_to_radiation: String
	number_of_cycles: String
	reason_treatment_ended: String
	route_of_administration: String
	treatment_arm: String
	treatment_dose: String
	treatment_dose_units: String
	treatment_effect_indicator: String
	treatment_frequency: String
}