type UIFile {
	file_id: String
	study_id: String
	pdc_study_id: String
	submitter_id_name: String
	embargo_date: Date	
	file_name: String
	study_run_metadata_submitter_id: String
	project_name: String
	data_category: String
	data_source: String
	file_type: String
	downloadable: String
	access: String
	md5sum: String
	file_size: String
}