type UIFilter {
	project_name: [UIFilterElement]
	primary_site: [UIFilterElement]
	program_name: [UIFilterElement]
	disease_type: [UIFilterElement]
	analytical_fraction: [UIFilterElement]
	experiment_type: [UIFilterElement]
	acquisition_type: [UIFilterElement]
	submitter_id_name: [UIFilterElement]
	sample_type: [UIFilterElement]
	ethnicity: [UIFilterElement]
	race: [UIFilterElement]
	gender: [UIFilterElement]
	tumor_grade: [UIFilterElement]
	data_category: [UIFilterElement]
	case_status: [UIFilterElement]
	vital_status: [UIFilterElement]
	age_at_diagnosis: [UIFilterElement]
	ajcc_clinical_stage: [UIFilterElement]
	ajcc_pathologic_stage: [UIFilterElement]
	morphology: [UIFilterElement]
	site_of_resection_or_biopsy: [UIFilterElement]
	progression_or_recurrence: [UIFilterElement]
	therapeutic_agents: [UIFilterElement]
	treatment_intent_type: [UIFilterElement]
	treatment_outcome: [UIFilterElement]
	treatment_type: [UIFilterElement]
	alcohol_history: [UIFilterElement]
	alcohol_intensity: [UIFilterElement]
	tobacco_smoking_status: [UIFilterElement]
	cigarettes_per_day: [UIFilterElement]
}

type UIFilterElement {
	filterName: String
	filterStudyCount: Int
	filterValue: [String]
}	
