type UIStudy {
	study_id: String
	study_submitter_id: String 
	pdc_study_id: String
	submitter_id_name: String
	study_description: String
	program_name: String
	project_name: String
	disease_type: String
	primary_site: String
	analytical_fraction: String
	experiment_type: String
	embargo_date: Date
	cases_count: Int
	aliquots_count: Int
	filesCount: [File]
	supplementaryFilesCount: [File]
	nonSupplementaryFilesCount: [File]
	contacts: [Contact]
	versions: [Version]
}